export const personal = {
  name: "M. Zohaib Safdar",
  shortName: "Zohaib",
  role: "Full-Stack Developer (MERN + AI)",
  tagline: "Building scalable web applications & AI-integrated systems",
  location: "Lahore, Pakistan",
  email: "za789688@gmail.com",
  phone: "+92 302-2375072",
  github: "https://github.com/x370",
  linkedin: "https://www.linkedin.com/in/zohaib-developer/",
  image: "/profile.jpg",
  resume: "/Zohaib_Safdar_Resume_Updated.pdf",
  years: 3,
  summary:
    "Full-Stack Developer with 3+ years of experience building end-to-end web applications using React.js, Next.js, Node.js, and NestJS, with hands-on experience integrating AI capabilities including RAG chatbots, LLM fine-tuning, and local model deployment (Ollama, GPT4All).",
};

export const stats = [
  { label: "Years of Experience", value: "3+", suffix: "" },
  { label: "Projects Delivered", value: "11", suffix: "+" },
  { label: "Clients Trained", value: "10", suffix: "+" },
  { label: "Bugs Resolved", value: "50", suffix: "+" },
];

export const skills = {
  languages: [
    { name: "JavaScript (ES6+)", level: 95 },
    { name: "TypeScript", level: 90 },
    { name: "Python", level: 75 },
    { name: "Go", level: 60 },
    { name: "Java", level: 60 },
  ],
  frontend: [
    { name: "React.js", level: 95 },
    { name: "Next.js", level: 92 },
    { name: "HTML5 / CSS3", level: 95 },
    { name: "SASS", level: 88 },
    { name: "Material UI", level: 85 },
    { name: "Tailwind CSS", level: 90 },
  ],
  backend: [
    { name: "Node.js", level: 92 },
    { name: "NestJS", level: 88 },
    { name: "Express.js", level: 90 },
    { name: "REST API Design", level: 93 },
    { name: "Microservices", level: 80 },
  ],
  databases: [
    { name: "MongoDB", level: 90 },
    { name: "MySQL", level: 85 },
    { name: "Redis", level: 82 },
    { name: "MongoDB Atlas (Vector)", level: 80 },
  ],
  devops: [
    { name: "Docker", level: 85 },
    { name: "GitHub Actions (CI/CD)", level: 82 },
    { name: "AWS", level: 75 },
    { name: "Git / GitHub", level: 95 },
    { name: "Linux", level: 80 },
  ],
  security: [
    { name: "Google OAuth 2.0", level: 90 },
    { name: "Microsoft OAuth 2.0", level: 88 },
    { name: "JWT", level: 92 },
    { name: "OWASP Guidelines", level: 80 },
  ],
  ai: [
    { name: "RAG (Retrieval-Augmented Gen.)", level: 82 },
    { name: "LLM Fine-Tuning", level: 75 },
    { name: "Ollama / GPT4All", level: 80 },
    { name: "Prompt Engineering", level: 85 },
    { name: "Agentic AI", level: 72 },
  ],
  platforms: [
    { name: "Zoho Creator (Low-Code/CRM)", level: 85 },
    { name: "DevOps Practices", level: 82 },
    { name: "GitHub Actions", level: 88 },
    { name: "Docker", level: 85 },
  ],
};

export const experience = [
  {
    company: "Arham Soft",
    role: "MERN Stack Developer — AI-Driven Products",
    project: "Growth Botz AI & AI-Integrated Web Platforms",
    duration: "May 2026 – Present",
    current: true,
    color: "primary",
    points: [
      "Building AI-driven automation products using MERN stack, integrating RAG pipelines, LLM fine-tuning, and agentic AI workflows (Ollama, GPT4All) into production web applications.",
      "Developed Growth Botz AI — a unified automation platform connecting multiple third-party tools and platform integrations into a single workspace.",
      "Engineered TeacherAI, a RAG-based chatbot with Google Classroom integration and MongoDB Atlas Vector Store for context-aware, document-grounded Q&A.",
      "Built PlusCareMD, an AI-powered healthcare platform enabling online patient consultations and appointment scheduling with real-time booking flows.",
    ],
  },
  {
    company: "Octek Pvt. Ltd.",
    role: "Full-Stack Developer",
    project: "Centurion — Papua New Guinea Government Web Application",
    duration: "April 2025 – May 2026",
    current: false,
    color: "accent",
    points: [
      "Developed a Next.js + TypeScript frontend with component-based architecture, improving page load speed by 25% and significantly enhancing the overall user experience across government modules.",
      "Integrated NestJS REST APIs with Google OAuth 2.0 and Microsoft OAuth 2.0 for secure multi-platform authentication and calendar event management.",
      "Migrated the entire raw SQL database layer to ORM across 15+ modules, cutting development time by 30% and improving code maintainability; restructured critical database schemas achieving 40% faster query execution.",
      "Designed and delivered a Government Licensing Management System with a Go backend for citizen-facing license application and tracking.",
      "Built WRB Country Population Management System — a national citizen registration platform with biometric fingerprint scanner integration and a Java PWA mobile app.",
    ],
  },
  {
    company: "Maima Soft",
    role: "React Frontend Developer",
    project: "Fuelbook — Fuel Management Software",
    duration: "March 2024 – April 2025",
    current: false,
    color: "gold",
    points: [
      "Engineered Fuelbook, a full-featured fuel management application using React.js with SASS styling, integrating RESTful APIs for real-time data flow and automating PDF report generation via the React PDF library.",
      "Architected a Redis caching layer integrated into the REST API backend, reducing repeated database round-trips and improving real-time dashboard response times by 30%.",
      "Built an EduBirds student visa consultancy web app for tracking application progress end-to-end.",
      "Developed an e-commerce platform and an investment management platform as key client deliverables.",
      "Conducted client training sessions covering all software modules, onboarding 10+ users and cutting post-launch support requests by 35%; diagnosed and resolved 50+ software bugs.",
    ],
  },
  {
    company: "Systems Limited",
    role: "Front-End Developer Intern",
    project: "React & Web Performance",
    duration: "December 2023 – March 2024",
    current: false,
    color: "primary",
    points: [
      "Delivered interactive UI components using HTML5, CSS3, and JavaScript achieving a 20% improvement in application performance; completed a full React.js e-commerce application as a key project milestone.",
      "Configured Git-based version control workflows with feature branching and pull request reviews, establishing consistent CI/CD practices and collaborative code standards across the intern team.",
      "Conducted competitive market research across 10+ rival products to inform strategic product roadmap decisions and identify enhancement opportunities.",
    ],
  },
];

export const projects = [
  {
    title: "Growth Botz AI",
    subtitle: "AI-Driven Automation Platform",
    year: "2026",
    description:
      "AI-powered automation platform that unifies multiple third-party tools and platform integrations into a single workspace. Built with MERN stack and agentic AI workflows for seamless business process automation.",
    tags: ["React.js", "Node.js", "NestJS", "MongoDB", "Agentic AI", "LLM", "REST API"],
    highlights: ["Multi-tool integration", "Agentic AI workflows", "Unified workspace"],
    featured: true,
    color: "primary",
    github: "",
    live: "",
  },
  {
    title: "TeacherAI",
    subtitle: "RAG-Based AI Education Chatbot",
    year: "2026",
    description:
      "RAG-based AI chatbot integrated with Google Classroom. Uses MongoDB Atlas Vector Store for document-grounded Q&A, allowing teachers and students to query course materials with context-aware AI responses.",
    tags: ["Next.js", "NestJS", "MongoDB Atlas", "RAG", "Google Classroom API", "LLM", "Vector DB"],
    highlights: ["Google Classroom sync", "Vector search", "Document-grounded Q&A"],
    featured: true,
    color: "accent",
    github: "",
    live: "",
  },
  {
    title: "PlusCareMD",
    subtitle: "AI-Powered Healthcare Platform",
    year: "2026",
    description:
      "AI-integrated healthcare platform enabling online patient checkups and appointment scheduling. Features real-time booking flows, AI-assisted consultation, and a patient management dashboard.",
    tags: ["React.js", "NestJS", "MongoDB", "AI Integration", "REST API", "TypeScript"],
    highlights: ["Online consultations", "AI-assisted checkups", "Real-time booking"],
    featured: true,
    color: "gold",
    github: "",
    live: "",
  },
  {
    title: "CalendarSk",
    subtitle: "Appointment & Calendar Management",
    year: "2025",
    description:
      "Full-stack appointment scheduling platform with Google & Microsoft OAuth 2.0 calendar sync, JWT refresh flows, and role-based access control following OWASP security guidelines.",
    tags: ["NestJS", "Next.js", "TypeScript", "OAuth 2.0", "JWT", "RBAC", "MongoDB"],
    highlights: ["Dual OAuth integration", "RBAC security", "JWT refresh"],
    featured: true,
    color: "primary",
    github: "",
    live: "",
  },
  {
    title: "Done Table",
    subtitle: "Real-Time Restaurant Reservation System",
    year: "2025",
    description:
      "Real-time restaurant reservation system with live table availability tracking, booking workflows, and RESTful API integration — deployed via Docker CI/CD pipeline on AWS.",
    tags: ["Next.js", "TypeScript", "Material UI", "Docker", "AWS", "REST API"],
    highlights: ["Live availability", "Real-time booking", "Docker + AWS CI/CD"],
    featured: false,
    color: "accent",
    github: "",
    live: "",
  },
  {
    title: "Government Licensing System",
    subtitle: "Papua New Guinea — Citizen License Portal",
    year: "2025",
    description:
      "Citizen-facing government license application and tracking system. Built with a Go backend for high-performance processing, integrated with the broader Centurion government platform.",
    tags: ["Go", "Next.js", "TypeScript", "REST API", "Government Grade"],
    highlights: ["Go backend", "Citizen portal", "License tracking"],
    featured: false,
    color: "gold",
    github: "",
    live: "",
  },
  {
    title: "WRB Population Management",
    subtitle: "National Citizen Registration Platform",
    year: "2025",
    description:
      "National citizen registration platform with biometric fingerprint scanner integration and a Java Progressive Web App (PWA) for mobile field officers.",
    tags: ["Java", "PWA", "Biometric Integration", "Next.js", "NestJS", "Government Grade"],
    highlights: ["Biometric fingerprint", "Java PWA", "National scale"],
    featured: false,
    color: "primary",
    github: "",
    live: "",
  },
  {
    title: "Fuelbook",
    subtitle: "Fuel Management Software",
    year: "2024",
    description:
      "Full-featured fuel tracking system built with React.js, real-time API integration, automated PDF reporting via React-PDF, and a Redis caching layer reducing dashboard response time by 30%.",
    tags: ["React.js", "SASS", "Redis", "React-PDF", "MongoDB", "REST API"],
    highlights: ["30% faster dashboard", "Auto PDF reports", "Redis caching"],
    featured: false,
    color: "accent",
    github: "",
    live: "",
  },
  {
    title: "EduBirds",
    subtitle: "Student Visa Consultancy Web App",
    year: "2024",
    description:
      "Student visa consultancy platform for tracking visa application progress end-to-end. Includes application submission, status tracking, document management, and consultant communication features.",
    tags: ["React.js", "Node.js", "MongoDB", "REST API", "SASS"],
    highlights: ["Application tracking", "Document management", "Consultant portal"],
    featured: false,
    color: "gold",
    github: "",
    live: "",
  },
  {
    title: "E-Commerce Platform",
    subtitle: "Full-Stack Shopping Experience — Maima Soft",
    year: "2024",
    description:
      "Full-featured e-commerce web application with product management, cart, checkout flow, and order tracking. Built with React.js frontend and Node.js backend with MongoDB.",
    tags: ["React.js", "Node.js", "MongoDB", "REST API", "Tailwind CSS"],
    highlights: ["Product management", "Cart & checkout", "Order tracking"],
    featured: false,
    color: "primary",
    github: "",
    live: "",
  },
  {
    title: "Investment Platform",
    subtitle: "Investment Management Dashboard — Maima Soft",
    year: "2024",
    description:
      "Investment portfolio management platform with real-time data visualization, portfolio tracking, and analytics dashboards built for financial clients.",
    tags: ["React.js", "Node.js", "MongoDB", "Charts.js", "REST API"],
    highlights: ["Portfolio tracking", "Real-time analytics", "Financial dashboards"],
    featured: false,
    color: "accent",
    github: "",
    live: "",
  },
];

export const education = {
  degree: "Bachelor of Science in Information Technology",
  school: "Lahore Garrison University, Lahore",
  duration: "2018 – 2023",
};

export const tools = [
  "Postman",
  "Swagger",
  "Jira",
  "Confluence",
  "VS Code",
  "GitHub Actions",
  "Docker",
  "Redis",
  "Zoho Creator",
  "Ollama",
  "GPT4All",
  "AWS",
];
